export const ATTRIBUTE_COLORS: Record<string, string> = {
  fire: "bg-orange-400 text-white",
  water: "bg-blue-400 text-white",
  grass: "bg-green-500 text-white",
  electric: "bg-yellow-300 text-gray-900",
  psychic: "bg-pink-400 text-white",
  ice: "bg-cyan-300 text-gray-900",
  dragon: "bg-indigo-600 text-white",
  dark: "bg-gray-700 text-white",
  fairy: "bg-pink-300 text-gray-900",
  fighting: "bg-red-600 text-white",
  flying: "bg-sky-400 text-white",
  poison: "bg-purple-500 text-white",
  ground: "bg-amber-600 text-white",
  rock: "bg-stone-500 text-white",
  bug: "bg-lime-500 text-white",
  ghost: "bg-violet-600 text-white",
  steel: "bg-slate-400 text-white",
  normal: "bg-gray-400 text-white",
};
